version: '3.8'

services:
  ifsdriveralert:
    build:
      context: .
      dockerfile: Dockerfile
    image: ferasaljoudi/ifsdriveralert:latest
    platform: linux/arm64
    ports:
      - "3000:3000"